name: CD - Main (deploy to MonsterASP via WebDeploy)

on:
  push:
    branches:
      - main   # Trigger this workflow whenever code is pushed to the 'main' branch

# This stops an old deployment immediately if a newer merge happens right after
concurrency:
  group: cd-main-${{ github.ref }}
  cancel-in-progress: true      

permissions:
  contents: read   # Limit this workflow to only read repository contents

jobs:
  build_and_deploy:
    runs-on: windows-latest   # WebDeploy action requires Windows for .NET publish with win-x86

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore ./src/UrlShortener/UrlShortener.csproj

      - name: Build
        run: dotnet build ./src/UrlShortener/UrlShortener.csproj --configuration Release --no-restore

      # already running the test in ci-de.yml so skipping it here
      #- name: Test   # Run tests before deploying
      #  run: dotnet test ./tests/UrlShortener.Tests/UrlShortener.Tests.csproj --configuration Release --no-build 
      
      - name: Publish
        run: dotnet publish ./src/UrlShortener/UrlShortener.csproj --configuration Release --output ./publish --runtime win-x86

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          # Points the action directly to our compiled output folder
          # source-path: ./publish
          # Using the absolute workspace path ensures MSDeploy doesn't get confused by '.' relative paths
          source-path: publish
          # Strips old files to prevent WebDeploy from running into locked file errors
          target-delete: true

      - name: Wait for restart
        shell: pwsh
        run: |
          Write-Host "Waiting 20 seconds for the app to restart...!"
          Start-Sleep -Seconds 20

      - name: Health Check (Admin)
        shell: pwsh
        run: |
          try {
            $response = Invoke-WebRequest -Uri "https://nikhilapi.runasp.net/api/Admin" -UseBasicParsing
            if ($response.StatusCode -eq 200) {
              Write-Host "Health check passed! App is alive. Hurray!"
            } else {
              throw "Unexpected status code: $($response.StatusCode)"
            }
          }
          catch {
            throw "Health check failed: $($_.Exception.Message)"
          }